.PHONY: clean All

All:
	@echo "----------Building project:[ 02_BreakAndContinue - Debug ]----------"
	@cd "02_BreakAndContinue" && $(MAKE) -f  "02_BreakAndContinue.mk"
clean:
	@echo "----------Cleaning project:[ 02_BreakAndContinue - Debug ]----------"
	@cd "02_BreakAndContinue" && $(MAKE) -f  "02_BreakAndContinue.mk" clean
