.PHONY: clean All

All:
	@echo "----------Building project:[ Step10_TypeCasts - Debug ]----------"
	@cd "Step10_TypeCasts" && $(MAKE) -f  "Step10_TypeCasts.mk"
clean:
	@echo "----------Cleaning project:[ Step10_TypeCasts - Debug ]----------"
	@cd "Step10_TypeCasts" && $(MAKE) -f  "Step10_TypeCasts.mk" clean
