.PHONY: clean All

All:
	@echo "----------Building project:[ 03_GetInput - Debug ]----------"
	@cd "03_GetInput" && $(MAKE) -f  "03_GetInput.mk"
clean:
	@echo "----------Cleaning project:[ 03_GetInput - Debug ]----------"
	@cd "03_GetInput" && $(MAKE) -f  "03_GetInput.mk" clean
