.PHONY: clean All

All:
	@echo "----------Building project:[ 04_NamingConventions - Debug ]----------"
	@cd "04_NamingConventions" && $(MAKE) -f  "04_NamingConventions.mk"
clean:
	@echo "----------Cleaning project:[ 04_NamingConventions - Debug ]----------"
	@cd "04_NamingConventions" && $(MAKE) -f  "04_NamingConventions.mk" clean
