.PHONY: clean All

All:
	@echo "----------Building project:[ 01_HelloWorld - Debug ]----------"
	@cd "01_HelloWorld" && $(MAKE) -f  "01_HelloWorld.mk"
clean:
	@echo "----------Cleaning project:[ 01_HelloWorld - Debug ]----------"
	@cd "01_HelloWorld" && $(MAKE) -f  "01_HelloWorld.mk" clean
