.PHONY: clean All

All:
	@echo "----------Building project:[ 05_Scope - Debug ]----------"
	@cd "05_Scope" && $(MAKE) -f  "05_Scope.mk"
clean:
	@echo "----------Cleaning project:[ 05_Scope - Debug ]----------"
	@cd "05_Scope" && $(MAKE) -f  "05_Scope.mk" clean
