.PHONY: clean All

All:
	@echo "----------Building project:[ 02_SwitchCase - Debug ]----------"
	@cd "02_SwitchCase" && $(MAKE) -f  "02_SwitchCase.mk"
clean:
	@echo "----------Cleaning project:[ 02_SwitchCase - Debug ]----------"
	@cd "02_SwitchCase" && $(MAKE) -f  "02_SwitchCase.mk" clean
