.PHONY: clean All

All:
	@echo "----------Building project:[ 03_FileSearchStr - Debug ]----------"
	@cd "03_FileSearchStr" && $(MAKE) -f  "03_FileSearchStr.mk"
clean:
	@echo "----------Cleaning project:[ 03_FileSearchStr - Debug ]----------"
	@cd "03_FileSearchStr" && $(MAKE) -f  "03_FileSearchStr.mk" clean
