.PHONY: clean All

All:
	@echo "----------Building project:[ 04_ReturnStrings - Debug ]----------"
	@cd "04_ReturnStrings" && $(MAKE) -f  "04_ReturnStrings.mk"
clean:
	@echo "----------Cleaning project:[ 04_ReturnStrings - Debug ]----------"
	@cd "04_ReturnStrings" && $(MAKE) -f  "04_ReturnStrings.mk" clean
