.PHONY: clean All

All:
	@echo "----------Building project:[ 02_CDdatabase - Debug ]----------"
	@cd "02_CDdatabase" && $(MAKE) -f  "02_CDdatabase.mk"
clean:
	@echo "----------Cleaning project:[ 02_CDdatabase - Debug ]----------"
	@cd "02_CDdatabase" && $(MAKE) -f  "02_CDdatabase.mk" clean
